{% set name = "ww" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: bb64211a6991fe9bc862365a4ec96790c367080ab184421281750a77e021959a

build:
  number: 0

test:
  commands:
    - ww

about:
  home: https://github.com/ESSS/ww
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The multiple-workspace batch script

extra:
  recipe-maintainers:
    - igortg
    - lvoliveira
