{% set name = "ww" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6e86a1d98f92b820189340eb10836b8e48a62605f7eaade5cbe3d4a12ff99766

build:
  number: 0

test:
  commands:
    - ww

about:
  home: https://github.com/ESSS/ww
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The multiple-workspace batch script

extra:
  recipe-maintainers:
    - igortg
    - lvoliveira
