{% set name = "ww" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: cd06f6742d85fb8a1bc0d892a61e57f55e5c9bbfa55015d6c70af037fb394337

build:
  number: 0

test:
  commands:
    - ww

about:
  home: https://github.com/ESSS/ww
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The multiple-workspace batch script

extra:
  recipe-maintainers:
    - igortg
    - lvoliveira
