{% set name = "ww" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b8bab6f866d5133e3a8352c24ab3ad2e3ff45585ff78a8d0e141a27a80146394

build:
  number: 0

test:
  commands:
    - ww

about:
  home: https://github.com/ESSS/ww
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The multiple-workspace batch script

extra:
  recipe-maintainers:
    - igortg
    - lvoliveira
