{% set name = "ww" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4bf5059124434fe8b77a18e5bfcfbe6aa20b5ea205d07c7862e201dda186fc4c

build:
  number: 0

test:
  commands:
    - ww

about:
  home: https://github.com/ESSS/ww
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The multiple-workspace batch script

extra:
  recipe-maintainers:
    - igortg
    - lvoliveira
